version: '3'

services:
  flask:
    build: .
    command: >
      sh -c "
        flask migrate
        flask scrap
        flask run -h 0.0.0.0 -p 8080"
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - SECRET_KEY=SECRET_KEY
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/luxonis_sreality
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=luxonis_sreality
    volumes:
      - luxonis_sreality_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  luxonis_sreality_data:
